// Code generated by _tmpl/utils.h.tmpl. DO NOT EDIT.

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// clang-format off
//go:build driverlib
// clang-format on

#pragma once

#include <stdlib.h>
#include "adbc.h"

struct AdbcError* QuackErrorFromArrayStream(struct ArrowArrayStream*, AdbcStatusCode*);
AdbcStatusCode QuackDatabaseGetOption(struct AdbcDatabase*, const char*, char*, size_t*,
                                      struct AdbcError*);
AdbcStatusCode QuackDatabaseGetOptionBytes(struct AdbcDatabase*, const char*, uint8_t*,
                                           size_t*, struct AdbcError*);
AdbcStatusCode QuackDatabaseGetOptionDouble(struct AdbcDatabase*, const char*, double*,
                                            struct AdbcError*);
AdbcStatusCode QuackDatabaseGetOptionInt(struct AdbcDatabase*, const char*, int64_t*,
                                         struct AdbcError*);
AdbcStatusCode QuackDatabaseInit(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode QuackDatabaseNew(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode QuackDatabaseRelease(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode QuackDatabaseSetOption(struct AdbcDatabase* db, const char* key,
                                      const char* value, struct AdbcError* err);
AdbcStatusCode QuackDatabaseSetOptionBytes(struct AdbcDatabase*, const char*,
                                           const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode QuackDatabaseSetOptionDouble(struct AdbcDatabase*, const char*, double,
                                            struct AdbcError*);
AdbcStatusCode QuackDatabaseSetOptionInt(struct AdbcDatabase*, const char*, int64_t,
                                         struct AdbcError*);

AdbcStatusCode QuackConnectionCancel(struct AdbcConnection*, struct AdbcError*);
AdbcStatusCode QuackConnectionCommit(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode QuackConnectionGetInfo(struct AdbcConnection* cnxn, const uint32_t* codes,
                                      size_t len, struct ArrowArrayStream* out,
                                      struct AdbcError* err);
AdbcStatusCode QuackConnectionGetObjects(struct AdbcConnection* cnxn, int depth,
                                         const char* catalog, const char* dbSchema,
                                         const char* tableName, const char** tableType,
                                         const char* columnName,
                                         struct ArrowArrayStream* out,
                                         struct AdbcError* err);
AdbcStatusCode QuackConnectionGetOption(struct AdbcConnection*, const char*, char*,
                                        size_t*, struct AdbcError*);
AdbcStatusCode QuackConnectionGetOptionBytes(struct AdbcConnection*, const char*,
                                             uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode QuackConnectionGetOptionDouble(struct AdbcConnection*, const char*,
                                              double*, struct AdbcError*);
AdbcStatusCode QuackConnectionGetOptionInt(struct AdbcConnection*, const char*, int64_t*,
                                           struct AdbcError*);
AdbcStatusCode QuackConnectionGetStatistics(struct AdbcConnection*, const char*,
                                            const char*, const char*, char,
                                            struct ArrowArrayStream*, struct AdbcError*);
AdbcStatusCode QuackConnectionGetStatisticNames(struct AdbcConnection*,
                                                struct ArrowArrayStream*,
                                                struct AdbcError*);
AdbcStatusCode QuackConnectionGetTableSchema(struct AdbcConnection* cnxn,
                                             const char* catalog, const char* dbSchema,
                                             const char* tableName,
                                             struct ArrowSchema* schema,
                                             struct AdbcError* err);
AdbcStatusCode QuackConnectionGetTableTypes(struct AdbcConnection* cnxn,
                                            struct ArrowArrayStream* out,
                                            struct AdbcError* err);
AdbcStatusCode QuackConnectionInit(struct AdbcConnection* cnxn, struct AdbcDatabase* db,
                                   struct AdbcError* err);
AdbcStatusCode QuackConnectionNew(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode QuackConnectionReadPartition(struct AdbcConnection* cnxn,
                                            const uint8_t* serialized,
                                            size_t serializedLen,
                                            struct ArrowArrayStream* out,
                                            struct AdbcError* err);
AdbcStatusCode QuackConnectionRelease(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode QuackConnectionRollback(struct AdbcConnection* cnxn,
                                       struct AdbcError* err);
AdbcStatusCode QuackConnectionSetOption(struct AdbcConnection* cnxn, const char* key,
                                        const char* val, struct AdbcError* err);
AdbcStatusCode QuackConnectionSetOptionBytes(struct AdbcConnection*, const char*,
                                             const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode QuackConnectionSetOptionDouble(struct AdbcConnection*, const char*, double,
                                              struct AdbcError*);
AdbcStatusCode QuackConnectionSetOptionInt(struct AdbcConnection*, const char*, int64_t,
                                           struct AdbcError*);

AdbcStatusCode QuackStatementBind(struct AdbcStatement* stmt, struct ArrowArray* values,
                                  struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode QuackStatementBindStream(struct AdbcStatement* stmt,
                                        struct ArrowArrayStream* stream,
                                        struct AdbcError* err);
AdbcStatusCode QuackStatementCancel(struct AdbcStatement*, struct AdbcError*);
AdbcStatusCode QuackStatementExecuteQuery(struct AdbcStatement* stmt,
                                          struct ArrowArrayStream* out, int64_t* affected,
                                          struct AdbcError* err);
AdbcStatusCode QuackStatementExecutePartitions(struct AdbcStatement* stmt,
                                               struct ArrowSchema* schema,
                                               struct AdbcPartitions* partitions,
                                               int64_t* affected, struct AdbcError* err);
AdbcStatusCode QuackStatementExecutePartitionsTrampoline(
    struct AdbcStatement* stmt, struct ArrowSchema* schema,
    struct AdbcPartitions* partitions, int64_t* affected, struct AdbcError* err);
AdbcStatusCode QuackStatementExecuteSchema(struct AdbcStatement*, struct ArrowSchema*,
                                           struct AdbcError*);
AdbcStatusCode QuackStatementGetOption(struct AdbcStatement*, const char*, char*, size_t*,
                                       struct AdbcError*);
AdbcStatusCode QuackStatementGetOptionBytes(struct AdbcStatement*, const char*, uint8_t*,
                                            size_t*, struct AdbcError*);
AdbcStatusCode QuackStatementGetOptionDouble(struct AdbcStatement*, const char*, double*,
                                             struct AdbcError*);
AdbcStatusCode QuackStatementGetOptionInt(struct AdbcStatement*, const char*, int64_t*,
                                          struct AdbcError*);
AdbcStatusCode QuackStatementGetParameterSchema(struct AdbcStatement* stmt,
                                                struct ArrowSchema* schema,
                                                struct AdbcError* err);
AdbcStatusCode QuackStatementNew(struct AdbcConnection* cnxn, struct AdbcStatement* stmt,
                                 struct AdbcError* err);
AdbcStatusCode QuackStatementPrepare(struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode QuackStatementRelease(struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode QuackStatementSetOption(struct AdbcStatement* stmt, const char* key,
                                       const char* value, struct AdbcError* err);
AdbcStatusCode QuackStatementSetOptionBytes(struct AdbcStatement*, const char*,
                                            const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode QuackStatementSetOptionDouble(struct AdbcStatement*, const char*, double,
                                             struct AdbcError*);
AdbcStatusCode QuackStatementSetOptionInt(struct AdbcStatement*, const char*, int64_t,
                                          struct AdbcError*);
AdbcStatusCode QuackStatementSetSqlQuery(struct AdbcStatement* stmt, const char* query,
                                         struct AdbcError* err);
AdbcStatusCode QuackStatementSetSubstraitPlan(struct AdbcStatement* stmt,
                                              const uint8_t* plan, size_t length,
                                              struct AdbcError* err);

AdbcStatusCode AdbcDriverQuackInit(int version, void* rawDriver, struct AdbcError* err);

static inline void QuackerrRelease(struct AdbcError* error) {
  if (error->release) {
    error->release(error);
    error->release = NULL;
  }
}

void Quack_release_error(struct AdbcError* error);

struct QuackError {
  char* message;
  char** keys;
  uint8_t** values;
  size_t* lengths;
  int count;
};

void QuackReleaseErrWithDetails(struct AdbcError* error);

int QuackErrorGetDetailCount(const struct AdbcError* error);
struct AdbcErrorDetail QuackErrorGetDetail(const struct AdbcError* error, int index);

int QuackArrayStreamGetSchemaTrampoline(struct ArrowArrayStream* stream,
                                        struct ArrowSchema* out);
int QuackArrayStreamGetNextTrampoline(struct ArrowArrayStream* stream,
                                      struct ArrowArray* out);
